package com.dankblossom;

import android.content.Context;
import android.util.Log;
import android.webkit.JavascriptInterface;
import android.webkit.WebView;

import com.google.android.gms.tasks.Task;
import com.google.android.play.integrity.IntegrityManager;
import com.google.android.play.integrity.IntegrityManagerFactory;
import com.google.android.play.integrity.IntegrityTokenRequest;
import com.google.android.play.integrity.IntegrityTokenResponse;

/**
 * PlayIntegrityBridge
 *
 * Exposes a JavaScript interface ("AndroidPlayIntegrity") to the WebView so that
 * the React web app can request a Play Integrity token and forward it to the
 * Cloudflare Worker verification endpoint.
 *
 * Register this bridge in your Activity / Fragment that hosts the WebView:
 *
 *   webView.addJavascriptInterface(
 *       new PlayIntegrityBridge(this, webView),
 *       "AndroidPlayIntegrity"
 *   );
 *
 * Uses the Classic Integrity API (single-step flow):
 *   requestIntegrityToken() – requests a token by providing a nonce
 */
public class PlayIntegrityBridge {

    private static final String TAG = "PlayIntegrityBridge";

    private final Context context;
    private final WebView webView;
    private final IntegrityManager integrityManager;
    private final long cloudProjectNumber;

    public PlayIntegrityBridge(Context context, WebView webView, long cloudProjectNumber) {
        this.context = context.getApplicationContext();
        this.webView = webView;
        this.cloudProjectNumber = cloudProjectNumber;

        // Create an instance of a manager.
        this.integrityManager = IntegrityManagerFactory.create(this.context);
    }

    /**
     * Called by the JavaScript layer to request an integrity token.
     *
     * Usage from JavaScript (see src/lib/playIntegrity.js):
     *   window.AndroidPlayIntegrity.requestIntegrityToken(nonce, callbackId)
     *
     * On success the native code calls back:
     *   window.__playIntegrityCallbacks[callbackId].resolve(token)
     *
     * On failure it calls back:
     *   window.__playIntegrityCallbacks[callbackId].reject(new Error(message))
     *
     * @param nonce      Base64url-encoded nonce generated by the web layer
     * @param callbackId Unique ID used to route the result back to the correct
     *                   Promise in the web layer
     */
    @JavascriptInterface
    public void requestIntegrityToken(final String nonce, final String callbackId) {
        // Request the integrity token by providing a nonce and the Cloud project number.
        Task<IntegrityTokenResponse> integrityTokenResponse =
                integrityManager.requestIntegrityToken(
                        IntegrityTokenRequest.builder()
                                .setNonce(nonce)
                                .setCloudProjectNumber(cloudProjectNumber)
                                .build());

        integrityTokenResponse
                .addOnSuccessListener(response -> {
                    String token = escapeJs(response.token());
                    String js = "window.__playIntegrityCallbacks['" + callbackId
                            + "'] && window.__playIntegrityCallbacks['" + callbackId
                            + "'].resolve('" + token + "');";
                    webView.post(() -> webView.evaluateJavascript(js, null));
                })
                .addOnFailureListener(e -> {
                    Log.e(TAG, "requestIntegrityToken failed", e);
                    dispatchError(callbackId,
                            e.getMessage() != null ? e.getMessage() : "Unknown error");
                });
    }

    /** Rejects the given callback in the JavaScript layer with the supplied error message. */
    private void dispatchError(String callbackId, String message) {
        String msg = escapeJs(message);
        String js = "window.__playIntegrityCallbacks['" + callbackId
                + "'] && window.__playIntegrityCallbacks['" + callbackId
                + "'].reject(new Error('" + msg + "'));";
        webView.post(() -> webView.evaluateJavascript(js, null));
    }

    /** Escapes single quotes and backslashes so the string is safe inside JS literals. */
    private static String escapeJs(String s) {
        return s.replace("\\", "\\\\").replace("'", "\\'");
    }
}
