package com.dankblossom;

import android.content.Context;
import android.util.Log;
import android.webkit.JavascriptInterface;
import android.webkit.WebView;

import com.google.android.play.core.integrity.IntegrityManagerFactory;
import com.google.android.play.core.integrity.PrepareIntegrityTokenRequest;
import com.google.android.play.core.integrity.StandardIntegrityManager;
import com.google.android.play.core.integrity.StandardIntegrityManager.StandardIntegrityTokenProvider;
import com.google.android.play.core.integrity.StandardIntegrityTokenRequest;

/**
 * PlayIntegrityBridge
 *
 * Exposes a JavaScript interface ("AndroidPlayIntegrity") to the WebView so that
 * the React web app can request a Play Integrity token and forward it to the
 * Cloudflare Worker verification endpoint.
 *
 * Register this bridge in your Activity / Fragment that hosts the WebView:
 *
 *   webView.addJavascriptInterface(
 *       new PlayIntegrityBridge(this, webView, CLOUD_PROJECT_NUMBER),
 *       "AndroidPlayIntegrity"
 *   );
 *
 * CLOUD_PROJECT_NUMBER is the numeric Google Cloud project number associated
 * with your app in the Google Play Console (Settings → Integrity API).
 *
 * Uses the Standard Integrity API (two-phase flow):
 *   1. prepareIntegrityToken() – warms up the token provider (called on construction)
 *   2. requestIntegrityToken() – requests a token using the prepared provider
 */
public class PlayIntegrityBridge {

    private static final String TAG = "PlayIntegrityBridge";

    private final Context context;
    private final WebView webView;
    private final long cloudProjectNumber;
    private final StandardIntegrityManager standardIntegrityManager;
    private volatile StandardIntegrityTokenProvider integrityTokenProvider;

    public PlayIntegrityBridge(Context context, WebView webView, long cloudProjectNumber) {
        this.context = context.getApplicationContext();
        this.webView = webView;
        this.cloudProjectNumber = cloudProjectNumber;

        // Create an instance of a StandardIntegrityManager.
        this.standardIntegrityManager = IntegrityManagerFactory.createStandard(this.context);

        // Prepare integrity token. Can be called once in a while to keep internal state fresh.
        prepareIntegrityToken();
    }

    /**
     * Prepares the integrity token provider. Called automatically on construction;
     * call again periodically to keep the provider's internal state fresh.
     */
    public void prepareIntegrityToken() {
        standardIntegrityManager.prepareIntegrityToken(
                PrepareIntegrityTokenRequest.builder()
                        .setCloudProjectNumber(cloudProjectNumber)
                        .build())
                .addOnSuccessListener(tokenProvider -> {
                    integrityTokenProvider = tokenProvider;
                })
                .addOnFailureListener(exception -> {
                    // Provider preparation failed; integrityTokenProvider remains null or stale.
                    // requestIntegrityToken() calls will be rejected until prepareIntegrityToken()
                    // succeeds. Call prepareIntegrityToken() again to retry.
                    Log.e(TAG, "prepareIntegrityToken failed", exception);
                });
    }

    /**
     * Called by the JavaScript layer to request an integrity token.
     *
     * Usage from JavaScript (see src/lib/playIntegrity.js):
     *   window.AndroidPlayIntegrity.requestIntegrityToken(requestHash, callbackId)
     *
     * On success the native code calls back:
     *   window.__playIntegrityCallbacks[callbackId].resolve(token)
     *
     * On failure it calls back:
     *   window.__playIntegrityCallbacks[callbackId].reject(new Error(message))
     *
     * @param requestHash Base64url-encoded hash of request-specific data generated by the web layer
     * @param callbackId  Unique ID used to route the result back to the correct
     *                    Promise in the web layer
     */
    @JavascriptInterface
    public void requestIntegrityToken(final String requestHash, final String callbackId) {
        // Take a local snapshot of the volatile field. integrityTokenProvider is write-once
        // (null → non-null) so a non-null snapshot is guaranteed to remain valid.
        StandardIntegrityTokenProvider provider = integrityTokenProvider;
        if (provider == null) {
            dispatchError(callbackId, "Integrity token provider not ready. Please try again shortly.");
            return;
        }

        provider.request(
                StandardIntegrityTokenRequest.builder()
                        .setRequestHash(requestHash)
                        .build())
                .addOnSuccessListener(response -> {
                    String token = escapeJs(response.token());
                    String js = "window.__playIntegrityCallbacks['" + callbackId
                            + "'] && window.__playIntegrityCallbacks['" + callbackId
                            + "'].resolve('" + token + "');";
                    webView.post(() -> webView.evaluateJavascript(js, null));
                })
                .addOnFailureListener(e -> {
                    dispatchError(callbackId,
                            e.getMessage() != null ? e.getMessage() : "Unknown error");
                });
    }

    /** Rejects the given callback in the JavaScript layer with the supplied error message. */
    private void dispatchError(String callbackId, String message) {
        String msg = escapeJs(message);
        String js = "window.__playIntegrityCallbacks['" + callbackId
                + "'] && window.__playIntegrityCallbacks['" + callbackId
                + "'].reject(new Error('" + msg + "'));";
        webView.post(() -> webView.evaluateJavascript(js, null));
    }

    /** Escapes single quotes and backslashes so the string is safe inside JS literals. */
    private static String escapeJs(String s) {
        return s.replace("\\", "\\\\").replace("'", "\\'");
    }
}
