name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: android

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --stacktrace --info

      - name: Generate keystore
        if: github.event_name == 'push'
        run: ./gradlew generateKeystore
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_PATH: ${{ github.workspace }}/android/release.jks

      - name: Verify keystore
        if: github.event_name == 'push'
        run: ./gradlew verifyKeystore
        env:
          KEYSTORE_PATH: ${{ github.workspace }}/android/release.jks

      - name: Build release version
        if: github.event_name == 'push'
        run: ./gradlew assembleRelease --stacktrace --info
        env:
          KEYSTORE_PATH: ${{ github.workspace }}/android/release.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}