name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --stacktrace --info

      - name: Generate keystore
        if: github.event_name == 'push'
        run: ./gradlew generateKeystore

      - name: Verify keystore
        if: github.event_name == 'push'
        run: ./gradlew verifyKeystore

      - name: Build release version
        if: github.event_name == 'push'
        run: ./gradlew assembleRelease --stacktrace --info